---
- hosts: server_instance
  vars:
    cluster_name: benchmark
    node_id: "a{{ play_hosts.index(inventory_hostname) }}"
    service_tls: true
    fabric_tls: true
    heartbeat_tls: true
    tls_name: aerospike.server
    tls_authenticate_client: "false"
    ca_file: /etc/pki/tls/certs/aerospike.ca.crt
    cert_file: /etc/pki/tls/certs/aerospike.server_RSA.crt
    key_file: /etc/pki/tls/private/aerospike.server_RSA.key
    cipher_suite: AES256-GCM-SHA384
    namespace: test
    replication_factor: 2
    storage_engine: device
    memory_size: 64G
    devices: ['/dev/nvme1n1', '/dev/nvme2n1']
    write_block_size: 128K
    encryption: aes-256
    encryption_key_file: /etc/aerospike/private/ns_test.key
    channel_rw_fds: 8 # default 8
    channel_rw_recv_threads: 8 # default 16
    send_threads: 8 # default 8
    logging_contexts:
      - context: any
        level: info
      - context: tls
        level: debug
      - context: socket
        level: info
      - context: security
        level: debug
      - context: namespace
        level: debug
  tasks:
  - name: set hostname
    become: yes
    hostname:
      name: "{{ cluster_name }}.{{ node_id }}"
    tags:
      - config
  - name: create private aerospike directory
    become: yes
    file:
      path: /etc/aerospike/private
      state: directory
      mode: '0700'
  - name: copy encryption key
    become: yes
    copy:
      src: files/ns_test.key
      dest: /etc/aerospike/private/ns_test.key
      mode: '0600'
    tags: 
      - config
      - ear
  - name: upload CA certificate
    become: yes
    copy:
      src: files/aerospike.ca.crt
      dest: /etc/pki/tls/certs/aerospike.ca.crt
      mode: '0644'
    tags:
      - tls
  - name: upload RSA server certificate
    become: yes
    copy:
      src: files/aerospike.server_RSA.crt
      dest: /etc/pki/tls/certs/aerospike.server_RSA.crt
      mode: '0644'
    tags:
      - tls
  - name: upload RSA server private key
    become: yes
    copy:
      src: files/aerospike.server_RSA.key
      dest: /etc/pki/tls/private/aerospike.server_RSA.key
      mode: '0644'
    tags:
      - tls
  - name: upload ECDH server certificate
    become: yes
    copy:
      src: files/aerospike.server_ECDH.crt
      dest: /etc/pki/tls/certs/aerospike.server_ECDH.crt
      mode: '0644'
    tags:
      - tls
  - name: upload ECDH server private key
    become: yes
    copy:
      src: files/aerospike.server_ECDH.key
      dest: /etc/pki/tls/private/aerospike.server_ECDH.key
      mode: '0644'
    tags:
      - tls
  - name: upload feture key
    become: yes
    copy:
      src: files/features.conf
      dest: /etc/aerospike/features.conf
      mode: '0644'
    tags:
      - config
  - name: upload aerospike config
    become: yes
    template:
      src: templates/aerospike.conf.j2
      dest: /etc/aerospike/aerospike.conf
      mode: '0644'
    tags:
      - config
  - name: start aerospike service if not started
    become: yes
    service:
      name: aerospike
      state: restarted
  - name: show configuration template output
    debug: msg={{ lookup('template', 'aerospike.conf.j2', convert_data=False).split('\n') }}
    tags:
      - config
