---
- hosts: client_instance
  tasks:
  - name: upload enum-ciphers
    become: yes
    copy:
      src: files/enum-ciphers
      dest: /usr/local/bin
      mode: '0755'
  - name: upload CA certificate
    become: yes
    copy:
      src: files/aerospike.ca.crt
      dest: /etc/pki/tls/certs/aerospike.ca.crt
      mode: '0644'
  - name: upload RSA client certificate
    become: yes
    copy:
      src: files/aerospike.client_RSA.chain.p12
      dest: /etc/pki/tls/private/aerospike.client_RSA.chain.p12
      mode: '0644'
  - name: upload ECDH client certificate
    become: yes
    copy:
      src: files/aerospike.client_ECDH.chain.p12
      dest: /etc/pki/tls/private/aerospike.client_ECDH.chain.p12
      mode: '0644'
  - name: remove old CA certificate Java TrustStore
    become: no
    file:
      path: /home/{{ ansible_user }}/aerospike-client-java/benchmarks/aerospike.ca.jks
      state: absent
  - name: add CA certificate to Java TrustStore
    become: no
    java_cert:
      cert_path: /etc/pki/tls/certs/aerospike.ca.crt
      cert_alias: aerospike.ca
      keystore_path: /home/{{ ansible_user }}/aerospike-client-java/benchmarks/aerospike.ca.jks
      keystore_pass: changeit
      keystore_create: yes
      state: present
  - name: remove old RSA client certificate Java KeyStore
    become: no
    file:
      path: /home/{{ ansible_user }}/aerospike-client-java/benchmarks/aerospike.client_RSA.jks
      state: absent
  - name: add RSA client certificate to Java KeyStore
    become: no
    java_cert:
      pkcs12_path: /etc/pki/tls/private/aerospike.client_RSA.chain.p12
      pkcs12_alias: aerospike.client
      pkcs12_password: changeit
      cert_alias: aerospike.client
      keystore_path: /home/{{ ansible_user }}/aerospike-client-java/benchmarks/aerospike.client_RSA.jks
      keystore_pass: changeit
      keystore_create: yes
      state: present
  - name: remove ECDH client certificate Java KeyStore
    become: no
    file:
      path: /home/{{ ansible_user }}/aerospike-client-java/benchmarks/aerospike.client_ECDH.jks
      state: absent
  - name: add ECDH client certificate to Java KeyStore
    become: no
    java_cert:
      pkcs12_path: /etc/pki/tls/private/aerospike.client_ECDH.chain.p12
      pkcs12_alias: aerospike.client
      pkcs12_password: changeit
      cert_alias: aerospike.client
      keystore_path: /home/{{ ansible_user }}/aerospike-client-java/benchmarks/aerospike.client_ECDH.jks
      keystore_pass: changeit
      keystore_create: yes
      state: present


